DOCTORS = [
    {"name": "Dr. Sarah Johnson", "specialty": "Cardiology", "rating": 4.8, "price": 150, "experience": 15},
    {"name": "Dr. Michael Chen", "specialty": "Cardiology", "rating": 4.9, "price": 200, "experience": 20},
    {"name": "Dr. Emily Rodriguez", "specialty": "Dermatology", "rating": 4.7, "price": 120, "experience": 10},
    {"name": "Dr. James Wilson", "specialty": "Dermatology", "rating": 4.6, "price": 100, "experience": 8},
    {"name": "Dr. Lisa Anderson", "specialty": "Neurology", "rating": 4.9, "price": 180, "experience": 18},
    {"name": "Dr. David Kim", "specialty": "Neurology", "rating": 4.5, "price": 140, "experience": 12},
    {"name": "Dr. Maria Garcia", "specialty": "Orthopedics", "rating": 4.8, "price": 160, "experience": 16},
    {"name": "Dr. Robert Taylor", "specialty": "Orthopedics", "rating": 4.7, "price": 130, "experience": 11},
    {"name": "Dr. Jennifer Lee", "specialty": "Gastroenterology", "rating": 4.9, "price": 170, "experience": 14},
    {"name": "Dr. William Brown", "specialty": "Gastroenterology", "rating": 4.6, "price": 110, "experience": 9},
    {"name": "Dr. Amanda White", "specialty": "Endocrinology", "rating": 4.8, "price": 155, "experience": 13},
    {"name": "Dr. Christopher Davis", "specialty": "Endocrinology", "rating": 4.7, "price": 125, "experience": 10},
    {"name": "Dr. Patricia Martinez", "specialty": "Pulmonology", "rating": 4.9, "price": 175, "experience": 17},
    {"name": "Dr. Daniel Thompson", "specialty": "Pulmonology", "rating": 4.5, "price": 135, "experience": 11},
    {"name": "Dr. Jessica Moore", "specialty": "Rheumatology", "rating": 4.7, "price": 145, "experience": 12},
    {"name": "Dr. Thomas Harris", "specialty": "General Medicine", "rating": 4.6, "price": 100, "experience": 15},
    {"name": "Dr. Rachel Green", "specialty": "General Medicine", "rating": 4.8, "price": 120, "experience": 12},
    {"name": "Dr. Steven Park", "specialty": "Dentistry", "rating": 4.9, "price": 90, "experience": 14},
    {"name": "Dr. Michelle Wong", "specialty": "Dentistry", "rating": 4.7, "price": 80, "experience": 10},
    {"name": "Dr. Kevin Foster", "specialty": "Ophthalmology", "rating": 4.8, "price": 140, "experience": 16},
    {"name": "Dr. Laura Bennett", "specialty": "Ophthalmology", "rating": 4.6, "price": 110, "experience": 11},
    {"name": "Dr. Richard Stone", "specialty": "Psychiatry", "rating": 4.9, "price": 160, "experience": 18},
    {"name": "Dr. Angela Cruz", "specialty": "Psychiatry", "rating": 4.7, "price": 130, "experience": 13},
    {"name": "Dr. Brian Murphy", "specialty": "Urology", "rating": 4.8, "price": 155, "experience": 15},
    {"name": "Dr. Sophia Turner", "specialty": "Gynecology", "rating": 4.9, "price": 145, "experience": 14},
]
